const BOT_NAME_POOL = [
  // Cute / đặt tên kiểu bạn bè
  'Bé Na',
  'Cu Tí',
  'Mèo Mun',
  'Sóc Nâu',
  'Tủn Mủn',
  'Bắp Rang',
  'Trà Sữa',
  'Bánh Bao',
  'Cún Bông',
  'Xoài Lắc',
  'Kem Chuối',
  'Bơ Sáp',
  'Chuối Chiên',
  'Mochi Trắng',
  'Táo Đỏ',
  'Cam Vàng',
  'Dưa Hấu',
  'Khoai Lang',
  'Bắp Cải',
  'Rau Muống',
  'Thịt Kho',
  'Cơm Tấm',
  'Phở Bò',
  'Bún Riêu',
  'Chè Khúc',
  'Sữa Chua',
  'Trà Đá',
  'Cà Phê Sữa',
  'Matcha Latte',
  'Bubble Tea',
  'Cờ Rin',

  // Hài / meme Việt
  'Cô Ba Sài Gòn',
  'Chú Tư Lúa',
  'Bà Tám',
  'Ông Năm Cờ',
  'Anh Hai Xóm',
  'Em Ba Phố',
  'Thằng Bạn Quê',
  'Con Nhà Hàng Xóm',
  'Tốc Độ Bàn Thờ',
  'Thánh Gõ Phím',
  'Cao Thủ Làng',
  'Pro Vãi',
  'Noob Thật',
  'Gà Con',
  'Cá Mập Nhỏ',
  'Sói Con',
  'Hổ Meo',
  'Vịt Lội',
  'Gà Mái',
  'Heo Con',
  'Cá Heo',
  'Rùa Biển',
  'Cua Đá',
  'Tôm Hùm',
  'Mực Xào',

  // Game / slang
  'Lucky Dice',
  'Pony Express',
  'Sir Gallop',
  'Captain Carrot',
  'Turbo Ngựa',
  'Win Liền',
  'Về Bờ',
  'Ngựa Hoang',
  'Phi Nước Đại',
  'Roll Master',
  'Dice God',
  'Lucky Roll',
  'Speed Run',
  'Clutch King',
  'Comeback Kid',
  'Trap Master',
  'Rune Hunter',
  'Card Shark',
  'Board Boss',
  'Final Lap',
  'Home Stretch',
  'Star Lane',
  'Safe Spot',
  'Trap Zone',
  'Swap Wizard',

  // Mix Anh-Việt tự nhiên
  'Mr Ngựa',
  'Miss Dice',
  'Boss Cuối',
  'Top 1 Server',
  'Mid Laner',
  'Carry Team',
  'Support Main',
  'One Trick',
  'Smurf Account',
  'Alt Account',
  'Casual Gamer',
  'Try Hard',
  'Chill Player',
  'Sweaty Hands',
  'Keyboard Warrior',
  'Mouse Drift',
  'Ping 999',
  'Lag Spike',
  'No Cap',
  'Low Key Pro',

  // Tên “người thật” hơn
  'Minh Anh',
  'Hoàng Long',
  'Thanh Tú',
  'Quốc Bảo',
  'Kim Ngân',
  'Tuấn Kiệt',
  'Phương Anh',
  'Đức Anh',
  'Hà My',
  'Bảo Châu',
  'Gaming VN',
  'Dice Roll VN',
  'Ludo Fan',
  'Board Game Lover',
  'Weekend Player',
  'Night Owl',
  'Early Bird',
  'Coffee Gamer',
  'Tea Time',
  'After School',

  // ===== Người thật Việt Nam =====
  'Gia Huy',
  'Khánh An',
  'Minh Khôi',
  'Nhật Minh',
  'Tuấn Anh',
  'Hoài Nam',
  'Quang Huy',
  'Trọng Nghĩa',
  'Bảo Minh',
  'Phúc An',
  'Mai Anh',
  'Ngọc Anh',
  'Khánh Linh',
  'Thu Trang',
  'Hải Yến',
  'Thanh Trúc',
  'Quỳnh Như',
  'Mỹ Duyên',
  'Thảo Vy',
  'Ngọc Hân',

  // ===== Username Việt kiểu online =====
  'boyhaiduong',
  'gacon2008',
  'meocon123',
  'khanhcute',
  'vitcon99',
  'banhbao22',
  'codonkhongem',
  'thichtrasua',
  'anhchanglangthang',
  'playervn',
  'nguoila',
  'toiyeugame',
  'vietpro',
  'nguoichoivui',
  'chimcanhcut',
  'thanhvienmoi',
  'khongbietgi',
  'choidao',
  'vietgamer',
  'banhmiopla',

  // ===== Tên quốc tế =====
  'Alex',
  'Emma',
  'Noah',
  'Olivia',
  'Liam',
  'Sophia',
  'Mason',
  'Lucas',
  'Ethan',
  'Chloe',
  'Ryan',
  'Ava',
  'Logan',
  'Mia',
  'Leo',
  'Grace',
  'Daniel',
  'Emily',
  'Jack',
  'Charlotte',

  // ===== Username quốc tế =====
  'ShadowFox',
  'PixelPanda',
  'NightWolf',
  'SilentRain',
  'BlueComet',
  'CrimsonBird',
  'FrostByte',
  'CloudRunner',
  'LuckyCat',
  'MoonWalker',
  'NovaStar',
  'DarkMochi',
  'Firefly',
  'GhostPixel',
  'NeonFox',
  'CosmicDuck',
  'SilverArrow',
  'CherryBlast',
  'TurboPenguin',
  'SleepyBear',

  // ===== Kiểu Discord / Steam =====
  'xXShadowXx',
  'NoobHunter',
  'AFKAgain',
  'JustRolling',
  'LuckyGuy42',
  'ProPlayer99',
  'SkillIssue',
  'GGWellPlayed',
  'OfflineSoon',
  'CoffeeAddict',
  'TouchGrass',
  'NotYourMain',
  'AltNumber3',
  'DiceEnjoyer',
  'CasualMonday',

  // ===== Tên Nhật (ít thôi) =====
  'Yuki',
  'Haru',
  'Sora',
  'Rin',
  'Aoi',
  'Hina',
  'Mio',
  'Yuna',
  'Ren',
  'Kaito',
  'Takumi',
  'Yuto',
  'Riku',
  'Shota',
  'Yui',
  'Miku',
  'Nanami',
  'Akari',
  'Hinata',
  'Haruka',

  // ===== Username Nhật/anime-style =====
  'SakuraTea',
  'NekoChan',
  'MochiNeko',
  'KitsuneFox',
  'RamenLover',
  'TokyoRain',
  'YoruNoHoshi',
  'HoshiChan',
  'ShibaSmile',
  'SenpaiPlayer',

  // ===== Người chơi bình thường =====
  'Guest123',
  'Anonymous',
  'PlayerOne',
  'PlayerTwo',
  'Visitor',
  'Newbie',
  'WeekendHero',
  'MorningPlayer',
  'EveningGamer',
  'RandomUser',
  'HappyPlayer',
  'LuckyVisitor',
  'JustForFun',
  'OneMoreGame',
  'LastRound',
]

/** Picks a random bot name not already used in the lobby. */
export function randomBotName(takenNames: string[], rng: () => number = Math.random): string {
  const taken = new Set(takenNames.map((n) => n.trim().toLowerCase()))
  const available = BOT_NAME_POOL.filter((n) => !taken.has(n.toLowerCase()))
  if (available.length > 0) {
    return available[Math.floor(rng() * available.length)]!
  }
  const base = BOT_NAME_POOL[Math.floor(rng() * BOT_NAME_POOL.length)]!
  return `${base} ${Math.floor(rng() * 90) + 10}`
}
